# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.2.0"

gem "rails", "~> 8.0"
gem "puma", "~> 6.4"
gem "grpc", "~> 1.62"
gem "google-protobuf", "~> 3.25"
gem "redis", "~> 5.3"
gem "jwt", "~> 2.9"
gem "rack-cors", "~> 2.0"
gem "bootsnap", require: false

group :development, :test do
  gem "debug"
  gem "rspec-rails", "~> 7.0"
  gem "grpc-tools", "~> 1.62"
end
